data_ingestion:
  raw_data_path: artifacts/raw_data.csv
  train_data_path: artifacts/train.csv
  test_data_path: artifacts/test.csv
  test_size: 0.2
  data_source_config_path: src/config/data_source.yaml
